//
//  Font.swift
//  fontDeneme
//
//  Created by Semih Emre ÜNLÜ on 30/09/2017.
//  Copyright © 2017 Semih Emre ÜNLÜ. All rights reserved.
//

import Foundation
import UIKit

public struct FontistoIcon {
    let name: String
    let unicode: [String]
    
    public init(name: String, unicode: [String]) {
        self.name = name
        self.unicode = unicode
    }
}

internal let font: [FontistoIcon] = [
     FontistoIcon(name: "500px", unicode:["\u{e90a}"]),
     FontistoIcon(name: "amazon", unicode:["\u{e90b}"]),
     FontistoIcon(name: "ampproject", unicode:["\u{e90c}"]),
     FontistoIcon(name: "android", unicode:["\u{e90d}"]),
     FontistoIcon(name: "angularjs", unicode:["\u{e90e}"]),
     FontistoIcon(name: "apple", unicode:["\u{e90f}"]),
     FontistoIcon(name: "behance", unicode:["\u{e910}"]),
     FontistoIcon(name: "bitbucket", unicode:["\u{e911}"]),
     FontistoIcon(name: "bluetooth-b", unicode:["\u{e912}"]),
     FontistoIcon(name: "cloudflare", unicode:["\u{e913}"]),
     FontistoIcon(name: "codepen", unicode:["\u{e914}"]),
     FontistoIcon(name: "css3", unicode:["\u{e915}"]),
     FontistoIcon(name: "dribbble", unicode:["\u{e916}"]),
     FontistoIcon(name: "dropbox", unicode:["\u{e917}"]),
     FontistoIcon(name: "facebook", unicode:["\u{e918}"]),
     FontistoIcon(name: "flickr", unicode:["\u{e919}"]),
     FontistoIcon(name: "foursquare", unicode:["\u{e91a}"]),
     FontistoIcon(name: "fi", unicode:["\u{e980}"]),
     FontistoIcon(name: "fontisto", unicode:["\u{e981}"]),
     FontistoIcon(name: "git", unicode:["\u{e91b}"]),
     FontistoIcon(name: "github", unicode:["\u{e91c}"]),
     FontistoIcon(name: "google-plus", unicode:["\u{e91d}"]),
     FontistoIcon(name: "google", unicode:["\u{e91e}"]),
     FontistoIcon(name: "hangout", unicode:["\u{e91f}"]),
     FontistoIcon(name: "houzz", unicode:["\u{e920}"]),
     FontistoIcon(name: "html5", unicode:["\u{e921}"]),
     FontistoIcon(name: "instagram", unicode:["\u{e922}"]),
     FontistoIcon(name: "java", unicode:["\u{e923}"]),
     FontistoIcon(name: "jquery", unicode:["\u{e924}"]),
     FontistoIcon(name: "jsfiddle", unicode:["\u{e925}"]),
     FontistoIcon(name: "linkedin", unicode:["\u{e926}"]),
     FontistoIcon(name: "linux", unicode:["\u{e927}"]),
     FontistoIcon(name: "magento", unicode:["\u{e928}"]),
     FontistoIcon(name: "maxcdn", unicode:["\u{e929}"]),
     FontistoIcon(name: "medium", unicode:["\u{e92a}"]),
     FontistoIcon(name: "meetup", unicode:["\u{e92b}"]),
     FontistoIcon(name: "nodejs", unicode:["\u{e92c}"]),
     FontistoIcon(name: "opencart", unicode:["\u{e92d}"]),
     FontistoIcon(name: "pinterest", unicode:["\u{e92e}"]),
     FontistoIcon(name: "playstation", unicode:["\u{e92f}"]),
     FontistoIcon(name: "python", unicode:["\u{e930}"]),
     FontistoIcon(name: "react", unicode:["\u{e931}"]),
     FontistoIcon(name: "reddit", unicode:["\u{e932}"]),
     FontistoIcon(name: "ruby", unicode:["\u{e933}"]),
     FontistoIcon(name: "sass", unicode:["\u{e934}"]),
     FontistoIcon(name: "skype", unicode:["\u{e935}"]),
     FontistoIcon(name: "slack", unicode:["\u{e936}"]),
     FontistoIcon(name: "snapchat", unicode:["\u{e937}"]),
     FontistoIcon(name: "soundcloud", unicode:["\u{e938}"]),
     FontistoIcon(name: "spotify", unicode:["\u{e939}"]),
     FontistoIcon(name: "stack-overflow", unicode:["\u{e93a}"]),
     FontistoIcon(name: "steam", unicode:["\u{e93b}"]),
     FontistoIcon(name: "stumbleupon", unicode:["\u{e93c}"]),
     FontistoIcon(name: "svn", unicode:["\u{e93d}"]),
     FontistoIcon(name: "swarm", unicode:["\u{e93e}"]),
     FontistoIcon(name: "tripadvisor", unicode:["\u{e93f}"]),
     FontistoIcon(name: "tumblr", unicode:["\u{e940}"]),
     FontistoIcon(name: "twitch", unicode:["\u{e941}"]),
     FontistoIcon(name: "twitter", unicode:["\u{e942}"]),
     FontistoIcon(name: "vimeo", unicode:["\u{e943}"]),
     FontistoIcon(name: "wetransfer", unicode:["\u{e944}"]),
     FontistoIcon(name: "whatsapp", unicode:["\u{e945}"]),
     FontistoIcon(name: "wifi-logo", unicode:["\u{e946}"]),
     FontistoIcon(name: "wikipedia", unicode:["\u{e947}"]),
     FontistoIcon(name: "windows", unicode:["\u{e948}"]),
     FontistoIcon(name: "wordpress", unicode:["\u{e949}"]),
     FontistoIcon(name: "xbox", unicode:["\u{e94a}"]),
     FontistoIcon(name: "yahoo", unicode:["\u{e94b}"]),
     FontistoIcon(name: "yelp", unicode:["\u{e94c}"]),
     FontistoIcon(name: "youtube-play", unicode:["\u{e94d}"]),
     FontistoIcon(name: "chrome", unicode:["\u{e94e}"]),
     FontistoIcon(name: "edge", unicode:["\u{e94f}"]),
     FontistoIcon(name: "firefox", unicode:["\u{e950}"]),
     FontistoIcon(name: "opera", unicode:["\u{e952}"]),
     FontistoIcon(name: "internet-explorer", unicode:["\u{e951}"]),
     FontistoIcon(name: "safari", unicode:["\u{e953}"]),
     FontistoIcon(name: "audio-description", unicode:["\u{e900}"]),
     FontistoIcon(name: "blind", unicode:["\u{e901}"]),
     FontistoIcon(name: "braille", unicode:["\u{e902}"]),
     FontistoIcon(name: "deaf", unicode:["\u{e903}"]),
     FontistoIcon(name: "fa-american-sign-language-interpreting", unicode:["\u{e904}"]),
     FontistoIcon(name: "low-vision", unicode:["\u{e906}"]),
     FontistoIcon(name: "tty", unicode:["\u{e907}"]),
     FontistoIcon(name: "universal-acces", unicode:["\u{e908}"]),
     FontistoIcon(name: "wheelchair", unicode:["\u{e909}"]),
     FontistoIcon(name: "area-chart", unicode:["\u{e954}"]),
     FontistoIcon(name: "bar-chart", unicode:["\u{e955}"]),
     FontistoIcon(name: "line-chart", unicode:["\u{e956}"]),
     FontistoIcon(name: "pie-chart-1", unicode:["\u{e957}"]),
     FontistoIcon(name: "pie-chart-2", unicode:["\u{e958}"]),
     FontistoIcon(name: "bitcoin", unicode:["\u{e959}"]),
     FontistoIcon(name: "dollar", unicode:["\u{e95a}"]),
     FontistoIcon(name: "euro", unicode:["\u{e95b}"]),
     FontistoIcon(name: "gbp", unicode:["\u{e95c}"]),
     FontistoIcon(name: "gg", unicode:["\u{e95d}"]),
     FontistoIcon(name: "ils", unicode:["\u{e95e}"]),
     FontistoIcon(name: "inr", unicode:["\u{e95f}"]),
     FontistoIcon(name: "krw", unicode:["\u{e960}"]),
     FontistoIcon(name: "rouble", unicode:["\u{e961}"]),
     FontistoIcon(name: "tl", unicode:["\u{e962}"]),
     FontistoIcon(name: "yen", unicode:["\u{e963}"]),
     FontistoIcon(name: "angle-dobule-down", unicode:["\u{e964}"]),
     FontistoIcon(name: "angle-dobule-left", unicode:["\u{e965}"]),
     FontistoIcon(name: "angle-dobule-right", unicode:["\u{e966}"]),
     FontistoIcon(name: "angle-dobule-up", unicode:["\u{e967}"]),
     FontistoIcon(name: "angle-down", unicode:["\u{e968}"]),
     FontistoIcon(name: "angle-left", unicode:["\u{e969}"]),
     FontistoIcon(name: "angle-right", unicode:["\u{e96a}"]),
     FontistoIcon(name: "angle-up", unicode:["\u{e96b}"]),
     FontistoIcon(name: "arrow-down-l", unicode:["\u{e96c}"]),
     FontistoIcon(name: "arrow-down", unicode:["\u{e96d}"]),
     FontistoIcon(name: "arrow-expand", unicode:["\u{e96e}"]),
     FontistoIcon(name: "arrow-h", unicode:["\u{e96f}"]),
     FontistoIcon(name: "arrow-left-l", unicode:["\u{e970}"]),
     FontistoIcon(name: "arrow-left", unicode:["\u{e971}"]),
     FontistoIcon(name: "arrow-move", unicode:["\u{e972}"]),
     FontistoIcon(name: "arrow-resize", unicode:["\u{e973}"]),
     FontistoIcon(name: "arrow-return-left", unicode:["\u{e974}"]),
     FontistoIcon(name: "arrow-return-right", unicode:["\u{e975}"]),
     FontistoIcon(name: "arrow-right-l", unicode:["\u{e976}"]),
     FontistoIcon(name: "arrow-right", unicode:["\u{e977}"]),
     FontistoIcon(name: "arrow-swap", unicode:["\u{e978}"]),
     FontistoIcon(name: "arrow-up-l", unicode:["\u{e979}"]),
     FontistoIcon(name: "arrow-up", unicode:["\u{e97a}"]),
     FontistoIcon(name: "arrow-v", unicode:["\u{e97b}"]),
     FontistoIcon(name: "caret-down", unicode:["\u{e97c}"]),
     FontistoIcon(name: "caret-left", unicode:["\u{e97d}"]),
     FontistoIcon(name: "caret-right", unicode:["\u{e97e}"]),
     FontistoIcon(name: "caret-up", unicode:["\u{e97f}"]),
     FontistoIcon(name: "checkbox-active", unicode:["\u{e982}"]),
     FontistoIcon(name: "checkbox-passive", unicode:["\u{e983}"]),
     FontistoIcon(name: "radio-btn-active", unicode:["\u{e984}"]),
     FontistoIcon(name: "radio-btn-passive", unicode:["\u{e985}"]),
     FontistoIcon(name: "genderless", unicode:["\u{e986}"]),
     FontistoIcon(name: "intersex", unicode:["\u{e987}"]),
     FontistoIcon(name: "mars-double", unicode:["\u{e988}"]),
     FontistoIcon(name: "mars-stroke-h", unicode:["\u{e989}"]),
     FontistoIcon(name: "mars-stroke-v", unicode:["\u{e98a}"]),
     FontistoIcon(name: "mars-stroke", unicode:["\u{e98b}"]),
     FontistoIcon(name: "mars", unicode:["\u{e98c}"]),
     FontistoIcon(name: "mercury", unicode:["\u{e98d}"]),
     FontistoIcon(name: "neuter", unicode:["\u{e98e}"]),
     FontistoIcon(name: "transgender-alt", unicode:["\u{e98f}"]),
     FontistoIcon(name: "transgender", unicode:["\u{e990}"]),
     FontistoIcon(name: "venus-double", unicode:["\u{e991}"]),
     FontistoIcon(name: "venus-mars", unicode:["\u{e992}"]),
     FontistoIcon(name: "venus", unicode:["\u{e993}"]),
     FontistoIcon(name: "dislike", unicode:["\u{e994}"]),
     FontistoIcon(name: "like", unicode:["\u{e995}"]),
     FontistoIcon(name: "american-express", unicode:["\u{e9d0}"]),
     FontistoIcon(name: "credit-card", unicode:["\u{e9d1}"]),
     FontistoIcon(name: "iyzigo", unicode:["\u{e9d3}"]),
     FontistoIcon(name: "mastercard", unicode:["\u{e9d4}"]),
     FontistoIcon(name: "paypal", unicode:["\u{e9d6}"]),
     FontistoIcon(name: "payu", unicode:["\u{e9d7}"]),
     FontistoIcon(name: "troy", unicode:["\u{e9d8}"]),
     FontistoIcon(name: "visa", unicode:["\u{e9d9}"]),
     FontistoIcon(name: "google-wallet", unicode:["\u{e9d2}"]),
     FontistoIcon(name: "paypal-p", unicode:["\u{e9d5}"]),
     FontistoIcon(name: "backward", unicode:["\u{e9da}"]),
     FontistoIcon(name: "eject", unicode:["\u{e9db}"]),
     FontistoIcon(name: "equalizer", unicode:["\u{e9dc}"]),
     FontistoIcon(name: "forward", unicode:["\u{e9dd}"]),
     FontistoIcon(name: "headphone", unicode:["\u{e9de}"]),
     FontistoIcon(name: "heart", unicode:["\u{e9df}"]),
     FontistoIcon(name: "mic", unicode:["\u{e9e0}"]),
     FontistoIcon(name: "music-note", unicode:["\u{e9e1}"]),
     FontistoIcon(name: "pause", unicode:["\u{e9e2}"]),
     FontistoIcon(name: "play-list", unicode:["\u{e9e3}"]),
     FontistoIcon(name: "play", unicode:["\u{e9e4}"]),
     FontistoIcon(name: "player-settings", unicode:["\u{e9e5}"]),
     FontistoIcon(name: "podcast", unicode:["\u{e9e6}"]),
     FontistoIcon(name: "random", unicode:["\u{e9e7}"]),
     FontistoIcon(name: "record", unicode:["\u{e9e8}"]),
     FontistoIcon(name: "star", unicode:["\u{e9e9}"]),
     FontistoIcon(name: "step-backwrad", unicode:["\u{e9ea}"]),
     FontistoIcon(name: "step-forward", unicode:["\u{e9eb}"]),
     FontistoIcon(name: "stop", unicode:["\u{e9ec}"]),
     FontistoIcon(name: "volume-down", unicode:["\u{e9ed}"]),
     FontistoIcon(name: "volume-mute", unicode:["\u{e9ee}"]),
     FontistoIcon(name: "volume-off", unicode:["\u{e9ef}"]),
     FontistoIcon(name: "volume-up", unicode:["\u{e9f0}"]),
     FontistoIcon(name: "circle-o-notch", unicode:["\u{e9f1}"]),
     FontistoIcon(name: "propeller-1", unicode:["\u{e9f2}"]),
     FontistoIcon(name: "propeller-2", unicode:["\u{e9f3}"]),
     FontistoIcon(name: "propeller-3", unicode:["\u{e9f4}"]),
     FontistoIcon(name: "propeller-4", unicode:["\u{e9f5}"]),
     FontistoIcon(name: "spinner-cog", unicode:["\u{e9f6}"]),
     FontistoIcon(name: "spinner-fidget", unicode:["\u{e9f7}"]),
     FontistoIcon(name: "spinner-refresh", unicode:["\u{e9f8}"]),
     FontistoIcon(name: "spinner-rotate-forward", unicode:["\u{e9f9}"]),
     FontistoIcon(name: "spinner", unicode:["\u{e9fa}"]),
     FontistoIcon(name: "automobile", unicode:["\u{e9fb}"]),
     FontistoIcon(name: "bicycle", unicode:["\u{e9fc}"]),
     FontistoIcon(name: "bus", unicode:["\u{e9fd}"]),
     FontistoIcon(name: "car", unicode:["\u{e9fe}"]),
     FontistoIcon(name: "helicopter", unicode:["\u{e9ff}"]),
     FontistoIcon(name: "metro", unicode:["\u{ea00}"]),
     FontistoIcon(name: "motorcycle", unicode:["\u{ea01}"]),
     FontistoIcon(name: "plane", unicode:["\u{ea02}"]),
     FontistoIcon(name: "rocket", unicode:["\u{ea03}"]),
     FontistoIcon(name: "ship", unicode:["\u{ea04}"]),
     FontistoIcon(name: "subway", unicode:["\u{ea05}"]),
     FontistoIcon(name: "taxi", unicode:["\u{ea06}"]),
     FontistoIcon(name: "train", unicode:["\u{ea07}"]),
     FontistoIcon(name: "truck", unicode:["\u{ea08}"]),
     FontistoIcon(name: "yacht", unicode:["\u{ea08}"]),
     FontistoIcon(name: "camera", unicode:["\u{e996}"]),
     FontistoIcon(name: "clock", unicode:["\u{e997}"]),
     FontistoIcon(name: "close-a", unicode:["\u{e998}"]),
     FontistoIcon(name: "code", unicode:["\u{e999}"]),
     FontistoIcon(name: "comment", unicode:["\u{e99a}"]),
     FontistoIcon(name: "commenting", unicode:["\u{e99b}"]),
     FontistoIcon(name: "comments", unicode:["\u{e99c}"]),
     FontistoIcon(name: "crop", unicode:["\u{e99d}"]),
     FontistoIcon(name: "cursor", unicode:["\u{e99e}"]),
     FontistoIcon(name: "database", unicode:["\u{e99f}"]),
     FontistoIcon(name: "date", unicode:["\u{e9a0}"]),
     FontistoIcon(name: "earth", unicode:["\u{e9a1}"]),
     FontistoIcon(name: "email", unicode:["\u{e9a2}"]),
     FontistoIcon(name: "eye", unicode:["\u{e9a3}"]),
     FontistoIcon(name: "famale", unicode:["\u{e9a4}"]),
     FontistoIcon(name: "favorite", unicode:["\u{e9a5}"]),
     FontistoIcon(name: "filter", unicode:["\u{e9a6}"]),
     FontistoIcon(name: "fire", unicode:["\u{e9a7}"]),
     FontistoIcon(name: "flag", unicode:["\u{e9a8}"]),
     FontistoIcon(name: "flash", unicode:["\u{e9a9}"]),
     FontistoIcon(name: "home", unicode:["\u{e9aa}"]),
     FontistoIcon(name: "link", unicode:["\u{e9ab}"]),
     FontistoIcon(name: "locked", unicode:["\u{e9ac}"]),
     FontistoIcon(name: "male", unicode:["\u{e9ad}"]),
     FontistoIcon(name: "minus-a", unicode:["\u{e9ae}"]),
     FontistoIcon(name: "more-v-a", unicode:["\u{e9af}"]),
     FontistoIcon(name: "more-v", unicode:["\u{e9b0}"]),
     FontistoIcon(name: "move-h-a", unicode:["\u{e9b1}"]),
     FontistoIcon(name: "move-h", unicode:["\u{e9b2}"]),
     FontistoIcon(name: "nav-icon-a", unicode:["\u{e9b3}"]),
     FontistoIcon(name: "nav-icon-grid-a", unicode:["\u{e9b4}"]),
     FontistoIcon(name: "nav-icon-grid", unicode:["\u{e9b5}"]),
     FontistoIcon(name: "nav-icon-list-a", unicode:["\u{e9b6}"]),
     FontistoIcon(name: "nav-icon-list", unicode:["\u{e9b7}"]),
     FontistoIcon(name: "nav-icon", unicode:["\u{e9b8}"]),
     FontistoIcon(name: "navigate", unicode:["\u{e9b9}"]),
     FontistoIcon(name: "paper-plane", unicode:["\u{e9ba}"]),
     FontistoIcon(name: "person", unicode:["\u{e9bb}"]),
     FontistoIcon(name: "persons", unicode:["\u{e9bc}"]),
     FontistoIcon(name: "picture", unicode:["\u{e9bd}"]),
     FontistoIcon(name: "plus-a", unicode:["\u{e9be}"]),
     FontistoIcon(name: "print", unicode:["\u{e9bf}"]),
     FontistoIcon(name: "quote-a-left", unicode:["\u{e9c0}"]),
     FontistoIcon(name: "quote-a-right", unicode:["\u{e9c1}"]),
     FontistoIcon(name: "quote-left", unicode:["\u{e9c2}"]),
     FontistoIcon(name: "quote-right", unicode:["\u{e9c3}"]),
     FontistoIcon(name: "reply", unicode:["\u{e9c4}"]),
     FontistoIcon(name: "rss", unicode:["\u{e9c5}"]),
     FontistoIcon(name: "scissors", unicode:["\u{e9c6}"]),
     FontistoIcon(name: "share-a", unicode:["\u{e9c7}"]),
     FontistoIcon(name: "share", unicode:["\u{e9c8}"]),
     FontistoIcon(name: "shield", unicode:["\u{ea0a}"]),
     FontistoIcon(name: "trash", unicode:["\u{e9c9}"]),
     FontistoIcon(name: "unlocked", unicode:["\u{e9ca}"]),
     FontistoIcon(name: "usb", unicode:["\u{e9cb}"]),
     FontistoIcon(name: "wifi", unicode:["\u{e9cc}"]),
     FontistoIcon(name: "world-o", unicode:["\u{e9cd}"]),
     FontistoIcon(name: "world", unicode:["\u{e9ce}"]),
     FontistoIcon(name: "zoom", unicode:["\u{e9cf}"]),
     FontistoIcon(name: "bold", unicode:["\u{ea0e}"]),
     FontistoIcon(name: "broken-link", unicode:["\u{ea0f}"]),
     FontistoIcon(name: "center-align", unicode:["\u{ea10}"]),
     FontistoIcon(name: "close", unicode:["\u{ea11}"]),
     FontistoIcon(name: "columns", unicode:["\u{ea12}"]),
     FontistoIcon(name: "copy", unicode:["\u{ea13}"]),
     FontistoIcon(name: "eraser", unicode:["\u{ea14}"]),
     FontistoIcon(name: "export", unicode:["\u{ea15}"]),
     FontistoIcon(name: "file-1", unicode:["\u{ea16}"]),
     FontistoIcon(name: "file-2", unicode:["\u{ea17}"]),
     FontistoIcon(name: "folder", unicode:["\u{ea18}"]),
     FontistoIcon(name: "font", unicode:["\u{ea19}"]),
     FontistoIcon(name: "import", unicode:["\u{ea1a}"]),
     FontistoIcon(name: "italic", unicode:["\u{ea1b}"]),
     FontistoIcon(name: "indent", unicode:["\u{ea1c}"]),
     FontistoIcon(name: "justify", unicode:["\u{ea1d}"]),
     FontistoIcon(name: "left-align", unicode:["\u{ea1e}"]),
     FontistoIcon(name: "link2", unicode:["\u{ea1f}"]),
     FontistoIcon(name: "list-1", unicode:["\u{ea20}"]),
     FontistoIcon(name: "list-2", unicode:["\u{ea21}"]),
     FontistoIcon(name: "outdent", unicode:["\u{ea22}"]),
     FontistoIcon(name: "paperclip", unicode:["\u{ea23}"]),
     FontistoIcon(name: "paragraph", unicode:["\u{ea24}"]),
     FontistoIcon(name: "paste", unicode:["\u{ea25}"]),
     FontistoIcon(name: "preview", unicode:["\u{ea26}"]),
     FontistoIcon(name: "print2", unicode:["\u{ea27}"]),
     FontistoIcon(name: "redo", unicode:["\u{ea28}"]),
     FontistoIcon(name: "right-align", unicode:["\u{ea29}"]),
     FontistoIcon(name: "save", unicode:["\u{ea2a}"]),
     FontistoIcon(name: "save-1", unicode:["\u{ea2b}"]),
     FontistoIcon(name: "scissors2", unicode:["\u{ea2c}"]),
     FontistoIcon(name: "strikethrough", unicode:["\u{ea2d}"]),
     FontistoIcon(name: "subscript", unicode:["\u{ea2e}"]),
     FontistoIcon(name: "table-1", unicode:["\u{ea30}"]),
     FontistoIcon(name: "table-2", unicode:["\u{ea31}"]),
     FontistoIcon(name: "text-height", unicode:["\u{ea32}"]),
     FontistoIcon(name: "text-width", unicode:["\u{ea33}"]),
     FontistoIcon(name: "underline", unicode:["\u{ea34}"]),
     FontistoIcon(name: "undo", unicode:["\u{ea35}"])
]

public class Fontisto : NSObject {
    
    static let instance = Fontisto()
    
    public override init() { }
    
    public func registerIconFont(with url: URL) -> Bool {
        if let fontData = try? Data(contentsOf: url) {
            if let provider = CGDataProvider(data: fontData as CFData) {
                var error: Unmanaged<CFError>?
                let font:CGFont = CGFont(provider)
                if (!CTFontManagerRegisterGraphicsFont(font, &error)) {
                    print(error.debugDescription)
                    return false
                } else {
                    return true
                }
            }
        } else {
            return false
        }
        return false
    }
 
    public func loadFont(size: CGFloat) -> UIFont? {
     
//        let bundle = Bundle(for: Fontisto.self)
//        let url = bundle.url(forResource: "Fontisto", withExtension: "ttf")!
//        
//        let isFontRegistered = self.registerIconFont(with: url)
//        
//        guard isFontRegistered else { return nil }
        if let font = UIFont(name: "fontisto", size: size) {
            return font
        } else {
            return nil
        }
    }

}
